accounts/urls.py
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path

from accounts.views import *

app_name = 'accounts'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path

from blog.feeds import LatestEntriesFeed
from blog.views import *

app_name = "blog"

urlpatterns = [
    path("", blog_view, name="blog_view"),
    path("<int:pid>", blog_single, name="single"),
    path("category/<str:cat_name>", blog_view, name="category"),
    path("tag/<str:tag_name>", blog_view, name="tag"),
    path("author/<str:author_username>", blog_view, name="author"),
    path("search/", blog_search, name="search"),
    path('rss/feed/', LatestEntriesFeed())
]

mysite/urls.py
import debug_toolbar
import django.contrib.auth.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include, re_path

from blog.sitemaps import BlogSitemap
from website.sitemaps import StaticViewSitemap
from website.views import maintenance_view

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("", include("website.urls")),
    path("blog/", include("blog.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("summernote/", include('django_summernote.urls')),
    path("captcha/", include('captcha.urls')),
    path('', include(django.contrib.auth.urls))
]

if settings.MAINTENANCE_MODE:
    urlpatterns.insert(0, re_path(r'^', maintenance_view, name='maintenance'))

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from website.views import *

app_name = 'website'

urlpatterns = [
    path("", index_view, name="index_view"),
    path("about/", about_view, name="about"),
    path("contact/", contact_view, name="contact"),
    path("newsletter/", newsletter_view, name="newsletter"),
]

accounts/models.py
# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class CustomAuthenticationForm(AuthenticationForm):
    error_messages = {
        'invalid_login': (
            "Please enter a correct (username or email) and password. Note that both "
            "fields may be case-sensitive."
        ),
    }

accounts/views.py
import re

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import render, redirect, reverse

from accounts.forms import CustomUserCreationForm, CustomAuthenticationForm


def is_valid_email(email):
    email_regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    return re.match(email_regex, email)


def email_to_username(email):
    try:
        user = User.objects.get(email=email)
        return user.username
    except User.DoesNotExist:
        return None


def login_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = CustomAuthenticationForm(request=request, data=request.POST.copy())
            login_data = form.data.get('username')
            is_email = is_valid_email(login_data)

            if is_email:
                username_from_email = email_to_username(login_data)
                if username_from_email:
                    form.data['username'] = username_from_email

            if form.is_valid():
                login_data = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(request, username=login_data, password=password)

                if user is not None:
                    login(request, user)
                    messages.add_message(request, messages.SUCCESS, f'{login_data} logged in successfully')
                    return redirect(reverse('website:index_view'))
                else:
                    messages.add_message(request, messages.ERROR, "Sorry, we couldn't log you in")
                    return redirect(reverse('website:index_view'))
        else:
            form = CustomAuthenticationForm()
        context = {'form': form}
        return render(request, 'accounts/login.html', context)
    else:
        return redirect(reverse('website:index_view'))


@login_required
def logout_view(request):
    logout(request)
    messages.add_message(request, messages.SUCCESS, 'Logged Out Successfully')
    return redirect(reverse('website:index_view'))


def is_user_exists(email, username):
    return User.objects.filter(Q(email=email) | Q(username=username)).exists()


def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            email = request.POST.get('email')
            username = request.POST.get('username')
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')

            if not is_valid_email(email):
                messages.add_message(request, messages.ERROR, 'Please enter a valid email address.')
                return redirect('accounts:signup')

            if is_user_exists(email, username):
                messages.add_message(request, messages.ERROR, 'This email or username is already in use.')
                return redirect('accounts:signup')

            form = CustomUserCreationForm({
                'username': username,
                'email': email,
                'password1': password1,
                'password2': password2,
            })

            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'User created Successfully')
                return redirect('accounts:login')
            else:
                messages.add_message(request, messages.ERROR, 'Sorry Something went wrong')

        else:
            form = CustomUserCreationForm()

        context = {'form': form}
        return render(request, 'accounts/signup.html', context)
    else:
        return redirect(reverse('website:index_view'))

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Login
{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/login_css.css' %}">
{% endblock %}
{% block content %}
    <!-- start banner Area -->
    <section class="about-banner relative">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">Login</h1>
                    <p class="text-white link-nav">
                        <a href="{% url 'website:index_view' %}">Home</a> <span class="lnr lnr-arrow-right"></span> <a
                            href="{% url 'accounts:login' %}">Login
                    </a>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->
    <section class="vh-100" style="margin-top: 20px; margin-bottom: 20px;">
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                         class="img-fluid" alt="Sample image">
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <form method="post" action="{% url 'accounts:login' %}">
                        {% csrf_token %}
                        <!-- Username input -->
                        <div class="form-outline mb-4">
                            <input type="text" id="form3Example3" name='username' class="form-control form-control-lg"
                                   placeholder="Enter a valid Username or Email"/>
                            <label class="form-label" for="form3Example3">Username or Email</label>
                        </div>

                        <!-- Password input -->
                        <div class="form-outline mb-3">
                            <input type="password" name="password" id="form3Example4"
                                   class="form-control form-control-lg"
                                   placeholder="Enter password"/>
                            <label class="form-label" for="form3Example4">Password</label>
                        </div>

                        <div class="d-flex justify-content-between align-items-center">
                            <!-- Checkbox -->
                            <div class="form-check mb-0">
                                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3"/>
                                <label class="form-check-label" for="form2Example3">
                                    Remember me
                                </label>
                            </div>
                            <a href="{% url 'accounts:password_reset' %}" class="text-warning">Forgot password?</a>
                        </div>

                        <div class="text-center text-lg-start mt-4 pt-2">
                            <button type="submit" class="btn btn-warning btn-lg"
                                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Login
                            </button>
                            <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a
                                    href="{% url 'accounts:signup' %}"
                                    class="text-warning">Register</a>
                            </p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    SignUp
{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/login_css.css' %}">
{% endblock %}
{% block content %}
    <!-- start banner Area -->
    <section class="about-banner relative">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">SignUp</h1>
                    <p class="text-white link-nav">
                        <a href="{% url 'website:index_view' %}">Home</a> <span class="lnr lnr-arrow-right"></span> <a
                            href="{% url 'accounts:signup' %}">SignUp
                    </a>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->
    <section class="vh-100" style="margin-top: 20px; margin-bottom: 20px;">
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                         class="img-fluid" alt="Sample image">
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <form method="post" action="{% url 'accounts:signup' %}">
                        {% csrf_token %}
                        <!-- Email input -->
                        <div class="form-outline mb-3">
                            <input type="email" id="form3Example2" name="email" class="form-control form-control-lg"
                                   placeholder="Enter your email"/>
                            <label class="form-label" for="form3Example2">Email</label>
                        </div>
                        <!-- Username input -->
                        <div class="form-outline mb-3">
                            <input type="text" id="form3Example3" name='username' class="form-control form-control-lg"
                                   placeholder="Enter a valid Username"/>
                            <label class="form-label" for="form3Example3">Username</label>
                        </div>

                        <!-- Password input -->
                        <div class="form-outline mb-2">
                            <input type="password" name="password1" id="form3Example4"
                                   class="form-control form-control-lg"
                                   placeholder="Enter password"/>
                            <label class="form-label" for="form3Example4">Password</label>
                        </div>

                        <!-- Password Confirmation input -->
                        <div class="form-outline mb-1">
                            <input type="password" name="password2" id="form3Example5"
                                   class="form-control form-control-lg"
                                   placeholder="Confirm password"/>
                            <label class="form-label" for="form3Example5">Password Confirmation</label>
                        </div>

                        <div class="d-flex justify-content-between align-items-center">
                            <!-- Checkbox -->
                            <div class="form-check mb-0">
                                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3"/>
                                <label class="form-check-label" for="form2Example3">
                                    Remember me
                                </label>
                            </div>
                        </div>

                        <div class="text-center text-lg-start mt-4 pt-2">
                            <button type="submit" class="btn btn-warning btn-lg"
                                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Register
                            </button>
                            <p class="small fw-bold mt-2 pt-1 mb-0">Already have an account? <a
                                    href="{% url 'accounts:login' %}"
                                    class="text-warning">Login</a>
                            </p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}